import { Card } from '@/components/ui/Card';
import { AISignalPanel } from '@/components/signals/AISignalPanel';

export function AISignals() {
  return (
    <div className="wm-page">
      <div className="wm-page-header">
        <div>
          <h1 className="wm-h1">AI Signals</h1>
          <p className="wm-sub">Signals generated by your AI analysis pipeline.</p>
        </div>
      </div>
      <Card title="Signals" subtitle="Live signals will appear when connected">
        <AISignalPanel signals={[]} />
      </Card>
      <style>{`
        .wm-page { display: flex; flex-direction: column; gap: 16px; }
        .wm-page-header { display: flex; align-items: center; justify-content: space-between; }
        .wm-h1 { margin: 0; font-size: 18px; font-weight: 700; }
        .wm-sub { margin: 2px 0 0; font-size: 12.5px; color: var(--text-2); }
      `}</style>
    </div>
  );
}